Fix analyze ignorehttpserrors flag
marmelab/greenframe-cli pull request #34
Opened 2023-02-03 11:39 UTC by floo51

- Upgrade playwright to latest
- Lock playwright version to avoid future incompatibilities
- Fix tests mechanism + some tests
- Fix ignoreHTTPSErrors on analyze command
- Test it

2023-02-03 13:25 UTC, fzaninotto requested changes
I'm not a fan of removing useful tests. I suggest you split the e2e tests between one file that tests without the server, and the other with the server (and that one is probably skipped for now)

2023-02-03 13:25 UTC, fzaninotto commented on .greenframe.e2e.multiple.yml
> -containers:
I believe the "multiple" scenario was designed to test multiple containers

2023-02-03 13:25 UTC, fzaninotto commented on e2e/index.js
> -        it('E2E: Should run an analysis and fail because account is suspended', async () => {
Why did you remove this one?

2023-02-03 13:25 UTC, fzaninotto commented on e2e/index.js
> -        it('E2E: Should fail because user has reached the project limit', async () => {
do not remove

2023-02-03 13:25 UTC, fzaninotto commented on e2e/index.js
> +        it.skip('E2E: Should fail because "container_broken" is not a running container', async () => {
linter warning for skipped tests

2023-02-03 13:25 UTC, fzaninotto commented on e2e/index.js
> +describe.skip('E2E: analyze command distant', () => {
same

2023-02-03 13:25 UTC, fzaninotto commented on package.json
> +        "test-e2e": "jest ./e2e/index.js --testTimeout 120000",
again, this is no longer an e2e test

2023-02-03 14:49 UTC, floo51 commented on e2e/index.js
> +const BASE_COMMAND = `./bin/run analyze`;
That's still an e2e tests, it tests the app workflow from beginning to end, when used without the SaaS service.

2023-02-03 15:43 UTC, fzaninotto commented
You must also bump the package version to have it republished

2023-02-06 08:23 UTC, fzaninotto approved these changes

2023-02-06 08:23 UTC, merged